<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Eloquent\Model;
use Faker\Factory as Faker;
class StudentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items =[ 
            ["year"=>4, "name" => "Ababiya Bedada Girma", "sex"=>"M", "id"=>"R/0001/08"],
            ["year"=>4, "name" => "Abduselam Ahmed Shifa", "sex"=>"M", "id"=>"R/0031/08"],
            ["year"=>4, "name" => "Abeba Gebreyohannes Gidey", "sex"=>"F", "id"=>"R/0036/08"],
            ["year"=>4, "name" => "Abeje Lambamo Lamduno", "sex"=>"M", "id"=>"R/0045/08"],
            ["year"=>4, "name" => "Abel Ashagrie Derbew", "sex"=>"M", "id"=>"R/0046/08"],
            ["year"=>4, "name" => "Abel Mesfin Akalu ", "sex"=>"M", "id"=>"R/0054/08"],
            ["year"=>4, "name" => "Abenezer Yohannes Hailu", "sex"=>"M", "id"=>"R/0064/08"],
            ["year"=>4, "name" => "Abraham Gizaw Sahile", "sex"=>"M", "id"=>"R/0072/08"],
            ["year"=>4, "name" => "Abreham Alemayehu Terefe", "sex"=>"M", "id"=>"R/00045/07"],
            ["year"=>4, "name" => "Abrehat Belay Lema", "sex"=>"F", "id"=>"R/0078/08"],
            ["year"=>4, "name" => "Abrham Gebremedhin Gebrekidan", "sex"=>"M", "id"=>"R/0081/08"],
            ["year"=>4, "name" => "Adam Wubalem Tashu", "sex"=>"M", "id"=>"R/0086/08"],
            ["year"=>4, "name" => "Adonay Yirga Gebru", "sex"=>"M", "id"=>"R/0101/08"],
            ["year"=>4, "name" => "Adugna Haile Dibaba", "sex"=>"M", "id"=>"R/0102/08"],
            ["year"=>4, "name" => "Aida Shemsu Sultan", "sex"=>"F", "id"=>"R/0114/08"],
            ["year"=>4, "name" => "Alemseged Teshome Eshetu", "sex"=>"M", "id"=>"R/0131/08"],
            ["year"=>4, "name" => "Amanuel Asfaw Zewde", "sex"=>"M", "id"=>"R/0142/08"],
            ["year"=>4, "name" => "Amanuel Adisu", "sex"=>"M", "id"=>"R/00091/07"],
            ["year"=>4, "name" => "Amanuel Gebre Boreshu", "sex"=>"M", "id"=>"R/00099/07"],
            ["year"=>4, "name" => "Amanuel Loeta Sapo", "sex"=>"M", "id"=>"R/0149/08"],
            ["year"=>4, "name" => "Amanuel Mebrahtu Gebreslasse ", "sex"=>"M", "id"=>"R/0150/08"],
            ["year"=>4, "name" => "Amanuel Mosisa Ejeta ", "sex"=>"M", "id"=>"R/0153/08"],
            ["year"=>4, "name" => "Amare Chekile Alemu ", "sex"=>"M", "id"=>"R/0161/08"],
            ["year"=>4, "name" => "Amir Kheiru Jemal", "sex"=>"M", "id"=>"R/0168/08"],
            ["year"=>4, "name" => "Antenyismu Yirsaw Wubete", "sex"=>"M", "id"=>"R/0177/08"],
            ["year"=>4, "name" => "Ashenafi Wada Wachamo", "sex"=>"M", "id"=>"R/00135/07"],
            ["year"=>4, "name" => "Atinkut Worku Mekonnen", "sex"=>"M", "id"=>"R/0197/08"],
            ["year"=>4, "name" => "Atsbha Mebrahtu Lemma", "sex"=>"M", "id"=>"R/0199/08"],
            ["year"=>4, "name" => "Awoke Kassaw Demssie", "sex"=>"M", "id"=>"R/0200/08"],
            ["year"=>4, "name" => "Barok Firew Ololo", "sex"=>"M", "id"=>"R/0220/08"],
            ["year"=>4, "name" => "Andualem Megose Desalegn", "sex"=>"M", "id"=>"R/0226/08"],
            ["year"=>4, "name" => "Befikadu Abebe Magnecho", "sex"=>"M", "id"=>"R/0228/08"],
            ["year"=>4, "name" => "Befikir Gezahegn Wondimu", "sex"=>"M", "id"=>"R/0229/08"],
            ["year"=>4, "name" => "Belay Eba Birasa ", "sex"=>"M", "id"=>"R/0234/08"],
            ["year"=>4, "name" => "Bereket Asfaw Demeke", "sex"=>"M", "id"=>"R/0242/08"],
            ["year"=>4, "name" => "Bereket Mathewos Gatiso", "sex"=>"M", "id"=>"R/0245/08"],
            ["year"=>4, "name" => "Bereket Zerihun Tadesse", "sex"=>"M", "id"=>"R/0248/08"],
            ["year"=>4, "name" => "Besufikad Shibru Hassen", "sex"=>"M", "id"=>"R/0255/08"],
            ["year"=>4, "name" => "Bethelhem Mesfin Teferra", "sex"=>"F", "id"=>"R/0267/08"],
            ["year"=>4, "name" => "Bethelihem Tadesse Tiku", "sex"=>"F", "id"=>"R/0268/08"],
            ["year"=>4, "name" => "Biniam Hailemariam Zebre", "sex"=>"M", "id"=>"R/0280/08"],
            ["year"=>4, "name" => "Biruk Ermias Erkalo", "sex"=>"M", "id"=>"R/0295/08"],
            ["year"=>4, "name" => "Biruk Mihiret Asnake", "sex"=>"M", "id"=>"R/1094/08"],
            ["year"=>4, "name" => "Bisrat Takelle Emnetu", "sex"=>"F", "id"=>"R/0306/08"],
            ["year"=>4, "name" => "Bisrat Tesfaye Gebre", "sex"=>"F", "id"=>"R/0307/08"],
            ["year"=>4, "name" => "Bushra Mustofa Abedri", "sex"=>"M", "id"=>"R/0317/08"],
            ["year"=>4, "name" => "Dame Hirpa Olika", "sex"=>"F", "id"=>"R/0330/08"],
            ["year"=>4, "name" => "Dawit Elias Keba", "sex"=>"M", "id"=>"R/0348/08"],
            ["year"=>4, "name" => "Dawit Lemma Legesse", "sex"=>"M", "id"=>"R/00272/07"],
            ["year"=>4, "name" => "Dawit Mechal Woldeyes", "sex"=>"M", "id"=>"R/0356/08"],
            ["year"=>4, "name" => "Debebe Asefa Edao", "sex"=>"M", "id"=>"R/0368/08"],
            ["year"=>4, "name" => "Desalegn Bushashe Godebo ", "sex"=>"M", "id"=>"R/0384/08"],
            ["year"=>4, "name" => "Duguma Yeshitla Habtemariam ", "sex"=>"M", "id"=>"R/0394/08"],
            ["year"=>4, "name" => "Edget Negussie Tilahun", "sex"=>"M", "id"=>"R/0399/08"],
            ["year"=>4, "name" => "Elias Alemayehu Kitaba", "sex"=>"M", "id"=>"R/0407/08"],
            ["year"=>4, "name" => "Nigussu Biratu Baruda", "sex"=>"M", "id"=>"R/00796/07"],
            ["year"=>4, "name" => "Elias Nursefa Mohammed ", "sex"=>"M", "id"=>"R/0409/08"],
            ["year"=>4, "name" => "Engida Lishan Gashaw ", "sex"=>"M", "id"=>"R/0426/08"],
            ["year"=>4, "name" => "Ermias Kefelegn Gossem", "sex"=>"M", "id"=>"R/0433/08"],
            ["year"=>4, "name" => "Ermiyas Kasahun Bizuayehu", "sex"=>"M", "id"=>"R/0436/08"],
            ["year"=>4, "name" => "Esubalew Getachew Menber", "sex"=>"M", "id"=>"R/0446/08"],
            ["year"=>4, "name" => "Etsehiwot Eshetu Ayele", "sex"=>"F", "id"=>"R/0447/08"],
            ["year"=>4, "name" => "Eyob Baryau Kiross", "sex"=>"M", "id"=>"R/0453/08"],
            ["year"=>4, "name" => "Fanuel Hassen Andeta", "sex"=>"M", "id"=>"R/0468/08"],
            ["year"=>4, "name" => "Fasil Getasew Ayalew", "sex"=>"M", "id"=>"R/0471/08"],
            ["year"=>4, "name" => "Feven Getu Tilahun", "sex"=>"F", "id"=>"R/0480/08"],
            ["year"=>4, "name" => "Feven Mulugeta Woldetsadik", "sex"=>"F", "id"=>"R/0481/08"],
            ["year"=>4, "name" => "Fikru Mamo Besha", "sex"=>"M", "id"=>"R/0495/08"],
            ["year"=>4, "name" => "Filimoi Worku Shifera ", "sex"=>"M", "id"=>"R/0497/08"],
            ["year"=>4, "name" => "Fillimon Gebrealif Weldegebreal", "sex"=>"M", "id"=>"R/0498/08"],
            ["year"=>4, "name" => "Fozia Nurye Mohammed", "sex"=>"F", "id"=>"R/0508/08"],
            ["year"=>4, "name" => "Galana Jote Sima ", "sex"=>"M", "id"=>"R/0513/08"],
            ["year"=>4, "name" => "Gelila Mesfin Kebede", "sex"=>"F", "id"=>"R/0529/08"],
            ["year"=>4, "name" => "Gezachew Amare Berhan", "sex"=>"M", "id"=>"R/0547/08"],
            ["year"=>4, "name" => "Getu Deboch Aga", "sex"=>"M", "id"=>"R/0546/08"],
            ["year"=>4, "name" => "Girma Moges Desta", "sex"=>"M", "id"=>"R/0550/08"],
            ["year"=>4, "name" => "Gudeta Mengistu Negesso ", "sex"=>"M", "id"=>"R/0554/08"],
            ["year"=>4, "name" => "Habtamu Bidira Abera", "sex"=>"M", "id"=>"R/00483/07"],
            ["year"=>4, "name" => "Habtamu Tesfaye Ayele", "sex"=>"M", "id"=>"R/0573/08"],
            ["year"=>4, "name" => "Habtamu Tolu Kitata", "sex"=>"M", "id"=>"R/0574/08"],
            ["year"=>4, "name" => "Habtamu Wossen Kassahun", "sex"=>"M", "id"=>"R/0575/08"],
            ["year"=>4, "name" => "Hailabe Tadesse Ahmed", "sex"=>"M", "id"=>"R/0582/08"],
            ["year"=>4, "name" => "Haymanot Tsegaye Andualem", "sex"=>"M", "id"=>"R/0617/08"],
            ["year"=>4, "name" => "Henok Endeshaw Getnet", "sex"=>"M", "id"=>"R/0626/08"],
            ["year"=>4, "name" => "Ephrem Demelash Demse", "sex"=>"M", "id"=>"R/0427/08"],
            ["year"=>4, "name" => "Heran Tsegaye Belachew", "sex"=>"F", "id"=>"R/0632/08"],
            ["year"=>4, "name" => "Heyo Guta Oda", "sex"=>"M", "id"=>"R/0638/08"],
            ["year"=>4, "name" => "Ibrahim Nasser Ata", "sex"=>"M", "id"=>"R/0652/08"],
            ["year"=>4, "name" => "Israel Hawaria Shume", "sex"=>"M", "id"=>"R/0659/08"],
            ["year"=>4, "name" => "Jemal Mohamedngus Abrahim", "sex"=>"M", "id"=>"R/0665/08"],
            ["year"=>4, "name" => "Kasa Mengesha Guji", "sex"=>"M", "id"=>"R/0687/08"],
            ["year"=>4, "name" => "Kebede Urgecha Gonfa", "sex"=>"M", "id"=>"R/0692/08"],
            ["year"=>4, "name" => "Kelemework Eshetu Assefa", "sex"=>"F", "id"=>"R/00597/07"],
            ["year"=>4, "name" => "Kelil Harar Kasim", "sex"=>"M", "id"=>"R/0695/08"],
            ["year"=>4, "name" => "Khalid Mohammed Abdi", "sex"=>"M", "id"=>"R/0703/08"],
            ["year"=>4, "name" => "Kibru Demeke Tadesse ", "sex"=>"M", "id"=>"R/0707/08"],
            ["year"=>4, "name" => "Kidist Alemayehu Bedada", "sex"=>"F", "id"=>"R/0709/08"],
            ["year"=>4, "name" => "Natanim Demiss Bekele", "sex"=>"F", "id"=>"R/0918/08"],
            ["year"=>4, "name" => "Kinfe Tadesse Chernet", "sex"=>"M", "id"=>"R/0724/08"],
            ["year"=>4, "name" => "Hawlet Esmael Abdullahi", "sex"=>"F", "id"=>"R/0613/08"],
            ["year"=>4, "name" => "Leul Dereje Bonsa", "sex"=>"M", "id"=>"R/0745/08"],
            ["year"=>4, "name" => "Leulseged Tilahun Tesera", "sex"=>"M", "id"=>"R/0748/08"],
            ["year"=>4, "name" => "Lioul Behailu Desta", "sex"=>"M", "id"=>"R/0754/08"],
            ["year"=>4, "name" => "Loza Birhan Assefa ", "sex"=>"F", "id"=>"R/0756/08"],
            ["year"=>4, "name" => "Maeruf Fetu Nassir", "sex"=>"M", "id"=>"R/0760/08"],
            ["year"=>4, "name" => "Margis Zelalem Tarekegn", "sex"=>"F", "id"=>"R/0772/08"],
            ["year"=>4, "name" => "Mathilda Giovanni Grisenti", "sex"=>"F", "id"=>"R/0778/08"],
            ["year"=>4, "name" => "Mebatsion Yifru Woldeyohannes", "sex"=>"F", "id"=>"R/0784/08"],
            ["year"=>4, "name" => "Melaku Fikre Berega", "sex"=>"M", "id"=>"R/1185/06"],
            ["year"=>4, "name" => "Melat Kebede Abraham", "sex"=>"F", "id"=>"R/0805/08"],
            ["year"=>4, "name" => "Menor Birhanu Tadesse", "sex"=>"F", "id"=>"R/0820/08"],
            ["year"=>4, "name" => "Meron Gebremariam Gidey", "sex"=>"F", "id"=>"R/0827/08"],
            ["year"=>4, "name" => "Meskerem Abebaw Workneh", "sex"=>"F", "id"=>"R/0835/08"],
            ["year"=>4, "name" => "Meron Tamrat Alemu", "sex"=>"F", "id"=>"R/0830/08"],
            ["year"=>4, "name" => "Michael Tesfaye Teshome", "sex"=>"M", "id"=>"R/0841/08"],
            ["year"=>4, "name" => "Mihiretab Taye Hordofa", "sex"=>"M", "id"=>"R/0847/08"],
            ["year"=>4, "name" => "Mohammed Hassen Wodaje", "sex"=>"M", "id"=>"R/0876/08"],
            ["year"=>4, "name" => "Mohammed Seid Adem", "sex"=>"M", "id"=>"R/0879/08"],
            ["year"=>4, "name" => "Mohammee Beharu Tegegn", "sex"=>"M", "id"=>"R/0880/08"],
            ["year"=>4, "name" => "Mukerem Ali Nur", "sex"=>"M", "id"=>"R/0887/08"],
            ["year"=>4, "name" => "Muluken Bogale Megersa", "sex"=>"M", "id"=>"R/0894/08"],
            ["year"=>4, "name" => "Mustefa Kamil Mohammed", "sex"=>"M", "id"=>"R/0905/08"],
            ["year"=>4, "name" => "Nathnael Belayneh Mengistie", "sex"=>"M", "id"=>"R/0926/08"],
            ["year"=>4, "name" => "Natnael Alemneh Hiruy", "sex"=>"M", "id"=>"R/0932/08"],
            ["year"=>4, "name" => "Natnael Ameha Yirgu", "sex"=>"M", "id"=>"R/0934/08"],
            ["year"=>4, "name" => "Natnael Tsegazeab Gebretsadik", "sex"=>"M", "id"=>"R/0943/08"],
            ["year"=>4, "name" => "Nazrawi Solomon Abera", "sex"=>"M", "id"=>"R/0944/08"],
            ["year"=>4, "name" => "Nebyou Elias Chernet", "sex"=>"M", "id"=>"R/0950/08"],
            ["year"=>4, "name" => "Newera Aman Aliyi", "sex"=>"M", "id"=>"R/0960/08"],
            ["year"=>4, "name" => "Olyad Temesgen Beyene ", "sex"=>"M", "id"=>"R/0977/08"],
            ["year"=>4, "name" => "Roba Mengesha Asefa", "sex"=>"M", "id"=>"R/0997/08"],
            ["year"=>4, "name" => "Samson Tsegay Beyene ", "sex"=>"M", "id"=>"R/1021/08"],
            ["year"=>4, "name" => "Samuel Eshetu Workneh", "sex"=>"M", "id"=>"R/1025/08"],
            ["year"=>4, "name" => "Seada Ahmed Siraj", "sex"=>"F", "id"=>"R/1037/08"],
            ["year"=>4, "name" => "Selamu Sinebo Silkebo", "sex"=>"M", "id"=>"R/1045/08"],
            ["year"=>4, "name" => "Semere Hiluf Gebremedhin", "sex"=>"M", "id"=>"R/1047/08"],
            ["year"=>4, "name" => "Semira Murad Redi", "sex"=>"F", "id"=>"R/1049/08"],
            ["year"=>4, "name" => "Muna Mengistu Bekele ", "sex"=>"F", "id"=>"R/0900/08"],
            ["year"=>4, "name" => "Shambel Mebratu Mekete", "sex"=>"M", "id"=>"R/1055/08"],
            ["year"=>4, "name" => "Siham Ahmed Hassen", "sex"=>"F", "id"=>"R/1064/08"],
            ["year"=>4, "name" => "Sipara Tadesse Korsa", "sex"=>"F", "id"=>"R/1065/08"],
            ["year"=>4, "name" => "Sisay Damtew Gugsa", "sex"=>"M", "id"=>"R/1069/08"],
            ["year"=>4, "name" => "Sisay Melaku Aberie", "sex"=>"M", "id"=>"R/1070/08"],
            ["year"=>4, "name" => "Solen Abera Deressa ", "sex"=>"M", "id"=>"R/1074/08"],
            ["year"=>4, "name" => "Solomon Tekleab Wasihun ", "sex"=>"M", "id"=>"R/1080/08"],
            ["year"=>4, "name" => "Solomon Wondale Mengistu", "sex"=>"M", "id"=>"R/1082/08"],
            ["year"=>4, "name" => "Surafel Zenebe Nigussie", "sex"=>"M", "id"=>"R/1090/08"],
            ["year"=>4, "name" => "Tadele Yideg Zerihun ", "sex"=>"M", "id"=>"R/1095/08"],
            ["year"=>4, "name" => "Tadesse Ketema Dadi", "sex"=>"M", "id"=>"R/1098/08"],
            ["year"=>4, "name" => "Taye Tasfu Hurisa", "sex"=>"M", "id"=>"R/1112/08"],
            ["year"=>4, "name" => "Teame Gebreabiyezgi Hayefom", "sex"=>"M", "id"=>"R/1113/08"],
            ["year"=>4, "name" => "Tedros Haileslassie Gebrezgabher", "sex"=>"M", "id"=>"R/1118/08"],
            ["year"=>4, "name" => "Teklat Fisseha Kidanemariam", "sex"=>"M", "id"=>"R/1124/08"],
            ["year"=>4, "name" => "Tesfaledet Buzuwork Gemechu", "sex"=>"M", "id"=>"R/1138/08"],
            ["year"=>4, "name" => "Tesfaye Gudeat Kebede", "sex"=>"M", "id"=>"R/1143/08"],
            ["year"=>4, "name" => "Tihetna Mesfin Gebeyehu", "sex"=>"F", "id"=>"R/1157/08"],
            ["year"=>4, "name" => "Tsion Habteslassie Assefa", "sex"=>"F", "id"=>"R/1189/08"],
            ["year"=>4, "name" => "Walelgn Dagne Bekele", "sex"=>"M", "id"=>"R/1199/08"],
            ["year"=>4, "name" => "Yabets Hailemariam Hailu", "sex"=>"M", "id"=>"R/1216/08"],
            ["year"=>4, "name" => "Yadesa Berchu Beriso", "sex"=>"M", "id"=>"R/1220/08"],
            ["year"=>4, "name" => "Yafet Girum Tesfaye", "sex"=>"M", "id"=>"R/1221/08"],
            ["year"=>4, "name" => "Yeabsera Endalkachew Asfaw", "sex"=>"M", "id"=>"R/1232/08"],
            ["year"=>4, "name" => "Yordanos Beneberu Demissie", "sex"=>"F", "id"=>"R/1264/08"],
            ["year"=>4, "name" => "Yordanos Negussie Anekeresa", "sex"=>"F", "id"=>"R/1266/08"],
            ["year"=>4, "name" => "Yunus Ali Hassen", "sex"=>"M", "id"=>"R/1274/08"],
            ["year"=>4, "name" => "Ziade Weldesialassie Kahsay", "sex"=>"M", "id"=>"R/1295/08"],

            ["year"=>5, "name" => "Abdisa Tekalign Duguma", "sex"=>"M", "id"=>"R/00009/07"],
            ["year"=>5, "name" => "Abeanezer Kapital Ketena", "sex"=>"M", "id"=>"R/02050/07"],
            ["year"=>5, "name" => "Abel Kibrom Mekonen", "sex"=>"M", "id"=>"R/00029/07"],
            ["year"=>5, "name" => "Abinet Gurmessa Gutema", "sex"=>"M", "id"=>"R/00038/07"],
            ["year"=>5, "name" => "Abraham Tadesse Negera", "sex"=>"M", "id"=>"R/00042/07"],
            ["year"=>5, "name" => "Abrham Mengistu Beyene", "sex"=>"M", "id"=>"R/00049/07"],
            ["year"=>5, "name" => "Alemayehu Girma Lema", "sex"=>"M", "id"=>"R/00077/07"],
            ["year"=>5, "name" => "Amanuel Legese Tadese", "sex"=>"M", "id"=>"R/00103/07"],
            ["year"=>5, "name" => "Atekelet Afework Teferi", "sex"=>"M", "id"=>"R/00142/07"],
            ["year"=>5, "name" => "Betelhem Yimar Nigatuu", "sex"=>"F", "id"=>"R/00188/07"],
            ["year"=>5, "name" => "Dilnegod Gebrechirstos Ergena", "sex"=>"M", "id"=>"R/00299/07"],
            ["year"=>5, "name" => "Endagegnehu Dansamo Tafesse", "sex"=>"M", "id"=>"R/00341/07"],
            ["year"=>5, "name" => "Eshita Addisu Berisso", "sex"=>"F", "id"=>"R/00354/07"],
            ["year"=>5, "name" => "Eyerusalem Berhanu Hika", "sex"=>"M", "id"=>"R/00368/07"],
            ["year"=>5, "name" => "Fikadu Filipos Shanko", "sex"=>"M", "id"=>"R/00401/07"],
            ["year"=>5, "name" => "Fisha Laiku Wube", "sex"=>"M", "id"=>"R/00420/07"],
            ["year"=>5, "name" => "Getu Lakew Amare", "sex"=>"M", "id"=>"R/00466/07"],
            ["year"=>5, "name" => "Girma Kebede Abdisa", "sex"=>"M", "id"=>"R/00470/07"],
            ["year"=>5, "name" => "Girmaye Yacha Yajila", "sex"=>"M", "id"=>"R/00471/07"],
            ["year"=>5, "name" => "Hanna Kebede Asfaw", "sex"=>"F", "id"=>"R/00511/07"],
            ["year"=>5, "name" => "Hayat Muzemil Abdela", "sex"=>"F", "id"=>"R/00516/07"],
            ["year"=>5, "name" => "Haymanot Gebeyehu Gaga", "sex"=>"F", "id"=>"R/00518/07"],
            ["year"=>5, "name" => "Henok Endeshaw Tesema", "sex"=>"M", "id"=>"R/00530/07"],
            ["year"=>5, "name" => "Henok Fikadu Biru", "sex"=>"M", "id"=>"R/00532/07"],
            ["year"=>5, "name" => "Hiwot Habtamu Aderaw", "sex"=>"F", "id"=>"R/00546/07"],
            ["year"=>5, "name" => "Kaleab Yidnekachew Girma", "sex"=>"M", "id"=>"R/00569/07"],
            ["year"=>5, "name" => "Kalkidan Samson Taffese", "sex"=>"F", "id"=>"R/00581/07"],
            ["year"=>5, "name" => "Kerose Abay Tafere", "sex"=>"M", "id"=>"R/00603/07"],
            ["year"=>5, "name" => "Kidist Berhanu Gebre", "sex"=>"M", "id"=>"R/00607/07"],
            ["year"=>5, "name" => "Lamesa Olika Hirpa", "sex"=>"M", "id"=>"R/00621/07"],
            ["year"=>5, "name" => "Mahlet Birhanu Hailu", "sex"=>"F", "id"=>"R/02825/07"],
            ["year"=>5, "name" => "Mengistu Abebe legesse", "sex"=>"M", "id"=>"R/00688/07"],
            ["year"=>5, "name" => "Merga Woldeyohannes Enkossa", "sex"=>"M", "id"=>"R/00691/07"],
            ["year"=>5, "name" => "Merhawi Solomon Gebrekidan", "sex"=>"M", "id"=>"R/00692/07"],
            ["year"=>5, "name" => "Mikiyas Tilahun Kebede", "sex"=>"M", "id"=>"R/00716/07"],
            ["year"=>5, "name" => "Misikir Damenu Tsegaye", "sex"=>"M", "id"=>"R/02819/07"],
            ["year"=>5, "name" => "Nardos Teklemariam Shewamene", "sex"=>"M", "id"=>"R/00771/07"],
            ["year"=>5, "name" => "Oda Nure Benti", "sex"=>"M", "id"=>"R/00807/07"],
            ["year"=>5, "name" => "Riad Musa Guye", "sex"=>"M", "id"=>"R/00827/07"],
            ["year"=>5, "name" => "Sabet Siraj Eshak", "sex"=>"F", "id"=>"R/00840/07"],
            ["year"=>5, "name" => "SANCHO MULU ABEBE", "sex"=>"M", "id"=>"R/1561/06"],
            ["year"=>5, "name" => "Sebbona Meteka Demisse", "sex"=>"M", "id"=>"R/1564/06"],
            ["year"=>5, "name" => "Tizita Daba Ayu", "sex"=>"F", "id"=>"R/00958/07"],
            ["year"=>5, "name" => "Wondimagegn Demisse Sulamo", "sex"=>"M", "id"=>"R/00995/07"],
            ["year"=>5, "name" => "Yared Teklewold Yemanewold", "sex"=>"M", "id"=>"R/01009/07"],
            ["year"=>5, "name" => "Yilkal Fikre Hailu", "sex"=>"M", "id"=>"R/01024/07"],
            ["year"=>5, "name" => "Zerihun Regasa Hunde", "sex"=>"M", "id"=>"R/01073/07"],
            ["year"=>5, "name" => "Ababiya Bayisa Kenate", "sex"=>"M", "id"=>"R/00001/07"],
            ["year"=>5, "name" => "Abel Tesfaye Getahun", "sex"=>"M", "id"=>"R/00030/07"],
            ["year"=>5, "name" => "Amanuel Mesfin Deribe", "sex"=>"M", "id"=>"R/00106/07"],
            ["year"=>5, "name" => "Bontu Berhanu Gebisa", "sex"=>"F", "id"=>"R/00232/07"],
            ["year"=>5, "name" => "Debela Kejela Dinka", "sex"=>"M", "id"=>"R/00277/07"],
            ["year"=>5, "name" => "Dereje Mulu Baye", "sex"=>"M", "id"=>"R/00294/07"],
            ["year"=>5, "name" => "Estifanos Leul Zeleke", "sex"=>"M", "id"=>"R/00360/07"],
            ["year"=>5, "name" => "Galata Girma Amante", "sex"=>"M", "id"=>"R/00436/07"],
            ["year"=>5, "name" => "Getachew Alemu Lolamo", "sex"=>"M", "id"=>"R/00457/07"],
            ["year"=>5, "name" => "Henok Adugna Reta", "sex"=>"M", "id"=>"R/00524/07"],
            ["year"=>5, "name" => "Kaleab Tebebe Tekelemariam", "sex"=>"M", "id"=>"R/00568/07"],
            ["year"=>5, "name" => "Mihiretu Kassaye Kemiro", "sex"=>"M", "id"=>"R/00712/07"],
            ["year"=>5, "name" => "Muluken Chifraye Molla", "sex"=>"M", "id"=>"R/00752/07"],
            ["year"=>5, "name" => "Nahusenay Twedros Getachew", "sex"=>"M", "id"=>"R/00766/07"],
            ["year"=>5, "name" => "Nebiyu Girma Kebede", "sex"=>"M", "id"=>"R/00785/07"],
            ["year"=>5, "name" => "Nuredin Siraj Bedane", "sex"=>"M", "id"=>"R/00803/07"],
            ["year"=>5, "name" => "Sammy Hassen Hussen", "sex"=>"M", "id"=>"R/00843/07"],
            ["year"=>5, "name" => "Samrawit Tewolde Rezene", "sex"=>"M", "id"=>"R/00847/07"],
            ["year"=>5, "name" => "Selamawit Mekonnen Wakgary", "sex"=>"F", "id"=>"R/00865/07"],
            ["year"=>5, "name" => "Simon Bekele Barassa", "sex"=>"M", "id"=>"R/00883/07"],
            ["year"=>5, "name" => "Sisay Darcho Henjero", "sex"=>"M", "id"=>"R/00889/07"],
            ["year"=>5, "name" => "Sitemera Tasfamekonnen Yadeta", "sex"=>"F", "id"=>"R/00891/07"],
            ["year"=>5, "name" => "Sitotaw Ayele Argago", "sex"=>"M", "id"=>"R/00892/07"],
            ["year"=>5, "name" => "Tsegaye Fekadu Gebreyes", "sex"=>"M", "id"=>"R/00968/07"],
            ["year"=>5, "name" => "Tsegaye Fikadu Weldemariyam", "sex"=>"M", "id"=>"R/00969/07"],
            ["year"=>5, "name" => "Yonas Endale Deti", "sex"=>"M", "id"=>"R/01038/07"],
            ["year"=>5, "name" => "Yonas Negash Tesfaye", "sex"=>"M", "id"=>"R/01040/07"],
            ["year"=>5, "name" => "Yonatane Fekadu Kebede", "sex"=>"M", "id"=>"R/01045/07"]
        ];
        $faker = Faker::create();
        foreach ($items as $key=>$item) {
            // $pass = $faker->randomElements($array = array ('c','s','e','a','s','t','u','1','2','3','4','5','6','7','8','9','0'), $count = 6);
            $pass = $faker->randomLetter.$faker->randomLetter.$faker->randomLetter.$faker->randomLetter.$faker->randomDigit.$faker->randomDigit; 
            $student  = \App\Models\Student::create([
                'name' => $item['name'],
                'email' => $faker->unique()->userName."@astuportal.net",
                'id_number' => $item['id'],
                'password' => Hash::make($pass), 
                'initial_password' => $pass,
                'remember_token' => str_random(10),
                'sex' => $item['sex'],
                'disability' => 0,
                'batch_year' => $item['year']
            ]);
            // $item = [
            //         'student_id' => $student->id,'academic_year_id' =>1,'semester' => 1,
            //         'year'=> $item['year'], 'group'=> 0, 'institution_id' => 1, 'institution_type' => 'department' ];
            // \Modules\Academic\Entities\Enroll::create($item);
        }
    }
}
